import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-32 pb-20">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-5xl font-bold text-foreground mb-8">Terms & Conditions</h1>

          <div className="prose prose-invert max-w-none space-y-8 text-foreground/80">
            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using HeHo, you accept and agree to be bound by the terms and provisions of this agreement. HeHo is a platform for building AI-powered chatbots, autonomous backends, and custom APIs. If you do not agree to abide by these terms, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">2. Service Description</h2>
              <p>
                HeHo provides a no-code platform and REST API for creating and managing:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>AI-powered chatbots and conversational agents</li>
                <li>Autonomous backend systems with database integration</li>
                <li>Custom REST API endpoints for data management</li>
                <li>Integration with Supabase databases and OpenRouter AI models</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">3. User Responsibilities</h2>
              <p>You are responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Maintaining the confidentiality of your HeHo API key</li>
                <li>Maintaining the confidentiality of your OpenRouter API key</li>
                <li>Maintaining the confidentiality of your Supabase credentials</li>
                <li>All activities that occur under your account</li>
                <li>Ensuring your use complies with all applicable laws and regulations</li>
                <li>Ensuring your use complies with OpenRouter and Supabase terms of service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">4. AI Models & OpenRouter</h2>
              <p>
                HeHo uses OpenRouter to provide access to 35+ AI models. You are responsible for complying with OpenRouter's Terms of Service. AI responses are generated by third-party models and may not always be accurate. HeHo is not responsible for:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>AI model hallucinations or errors</li>
                <li>OpenRouter service outages or limitations</li>
                <li>Accuracy or quality of AI-generated responses</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">5. Data & Privacy</h2>
              <p>
                HeHo stores only authentication data and chatbot configuration in our Supabase instance. Your chatbot data, database connections, and business data are stored exclusively in your own Supabase project. We do not share your data with third parties except as necessary for operation:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>OpenRouter receives prompts and context for AI processing</li>
                <li>Supabase stores your database schemas and data under your control</li>
                <li>No data is used for training or improvement of our systems</li>
                <li>Your data remains under your ownership and control at all times</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">6. Database Permissions & Autonomous Operations</h2>
              <p>
                When you enable autonomous backend features, you grant HeHo's AI agents permission to perform specific operations on your database. You are responsible for:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Configuring appropriate permissions for each chatbot and agent</li>
                <li>Regularly reviewing and auditing autonomous operations</li>
                <li>Disabling write permissions if you only want read-only access</li>
                <li>Understanding that autonomous operations may modify your data</li>
                <li>Maintaining backups of critical data</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">7. Prohibited Use</h2>
              <p>You may not use HeHo for:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Creating illegal content or facilitating illegal activities</li>
                <li>Generating misinformation, disinformation, or deceptive content</li>
                <li>Scraping or harvesting personal data without consent</li>
                <li>Harassment, abuse, or discrimination</li>
                <li>Attempting to circumvent usage limits or security measures</li>
                <li>Unauthorized access to other users' data or systems</li>
                <li>Any activity that violates OpenRouter's or Supabase's terms</li>
                <li>Creating autonomous systems that harm or endanger users</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">8. REST API Usage</h2>
              <p>
                HeHo provides a REST API for programmatic access to chatbot management and database operations. API users must:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Never expose API keys in client-side code or public repositories</li>
                <li>Comply with rate limits and usage quotas</li>
                <li>Not use the API to circumvent platform limitations</li>
                <li>Accept responsibility for all API requests made with their credentials</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">9. Limitation of Liability</h2>
              <p>HeHo is provided on an "as-is" basis. We are not responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Data loss or corruption</li>
                <li>AI model hallucinations or errors</li>
                <li>Third-party service outages (OpenRouter, Supabase)</li>
                <li>Unauthorized access due to compromised credentials</li>
                <li>Your use of the service in violation of these terms</li>
                <li>Consequences of autonomous backend operations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">10. Changes to Service</h2>
              <p>
                HeHo reserves the right to modify or discontinue the service at any time. We will provide 30 days notice for major changes that negatively impact functionality. We may make emergency changes to address security issues or prevent service disruption without prior notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">11. Termination</h2>
              <p>
                We may terminate your account if you violate these terms or engage in prohibited use. You may delete your account at any time from your account settings. Upon termination, you remain responsible for any autonomous operations that were in progress.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">12. Indemnification</h2>
              <p>
                You agree to indemnify and hold harmless HeHo, Sparrow AI Solutions, and their officers, employees, and agents from any claims, damages, or costs arising from your use of the service, your violation of these terms, or your violation of any third-party rights.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">13. Contact</h2>
              <p>For questions about these terms, please contact: legal@heho.dev</p>
            </section>

            <div className="text-sm text-muted-foreground mt-12">
              <p>Last updated: March 2026</p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
